#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]
// Suppress warnings from code generated by bindgen
#![allow(unnecessary_transmutes)]

// Include the generated bindings
include!(concat!(env!("OUT_DIR"), "/bindings.rs"));
